FROM pimcore/pimcore:php8.5-supervisord-5.x

WORKDIR /var/www/html

COPY composer.json composer.lock ./
RUN COMPOSER_HOME=/tmp/composer composer install \
    --no-dev --optimize-autoloader --no-interaction --no-scripts

COPY . .

COPY .docker/messenger.railway.yaml config/packages/messenger_pimcore.yaml
COPY .docker/supervisord.conf /etc/supervisor/conf.d/pimcore.conf

RUN mkdir -p var/cache var/log var/assets var/tmp/thumbnails public/var \
    && chown -R www-data:www-data var public/var

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]
