<?php

/**
 * Inheritance: no
 * Variants: no
 *
 * Fields Summary:
 * - orderNumber [input]
 * - email [input]
 * - status [select]
 * - tier [manyToOneRelation]
 * - quantity [numeric]
 * - totalPrice [numeric]
 */

return \Pimcore\Model\DataObject\ClassDefinition::__set_state([
    'id' => 'order',
    'name' => 'Order',
    'title' => '',
    'description' => '',
    'creationDate' => null,
    'modificationDate' => null,
    'userOwner' => null,
    'userModification' => null,
    'parentClass' => '',
    'implementsInterfaces' => null,
    'listingParentClass' => '',
    'useTraits' => '',
    'listingUseTraits' => '',
    'allowInherit' => false,
    'allowVariants' => false,
    'showVariants' => false,
    'layoutDefinitions' =>
    \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
        'name' => 'pimcore_root',
        'type' => null,
        'region' => null,
        'title' => null,
        'width' => 0,
        'height' => 0,
        'collapsible' => false,
        'collapsed' => false,
        'bodyStyle' => null,
        'datatype' => 'layout',
        'permissions' => null,
        'children' => [
            \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
                'name' => 'Layout',
                'type' => null,
                'region' => null,
                'title' => '',
                'width' => 0,
                'height' => 0,
                'collapsible' => false,
                'collapsed' => false,
                'bodyStyle' => null,
                'datatype' => 'layout',
                'permissions' => null,
                'children' => [
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state([
                        'name' => 'orderNumber',
                        'title' => 'Order Number',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => true,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'input',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => true,
                        'maxLength' => 255,
                        'showCharCount' => false,
                        'columnLength' => 190,
                        'defaultValue' => '',
                        'enforceUniqueValues' => true,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state([
                        'name' => 'email',
                        'title' => 'Email',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => true,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'input',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => true,
                        'maxLength' => 255,
                        'showCharCount' => false,
                        'columnLength' => 190,
                        'defaultValue' => '',
                        'enforceUniqueValues' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state([
                        'name' => 'status',
                        'title' => 'Status',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'select',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => true,
                        'options' => [
                            ['key' => 'Pending',   'value' => 'pending'],
                            ['key' => 'Confirmed', 'value' => 'confirmed'],
                            ['key' => 'Expired',   'value' => 'expired'],
                            ['key' => 'Cancelled', 'value' => 'cancelled'],
                        ],
                        'defaultValue' => 'pending',
                        'columnLength' => 190,
                        'dynamicOptions' => false,
                        'enforceValidation' => true,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\ManyToOneRelation::__set_state([
                        'name' => 'tier',
                        'title' => 'Ticket Tier',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => true,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'manyToOneRelation',
                        'relationType' => true,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'classes' => [
                            ['classes' => 'TicketTier'],
                        ],
                        'assetTypes' => [],
                        'documentTypes' => [],
                        'objectsAllowed' => true,
                        'assetsAllowed' => false,
                        'documentsAllowed' => false,
                        'assetInlineDownloadAllowed' => false,
                        'allowToClearRelation' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state([
                        'name' => 'quantity',
                        'title' => 'Quantity',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => true,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'numeric',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'width' => '',
                        'defaultValue' => null,
                        'integer' => true,
                        'unsigned' => true,
                        'minValue' => 1,
                        'maxValue' => null,
                        'unique' => false,
                        'decimalSize' => null,
                        'decimalPrecision' => null,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state([
                        'name' => 'totalPrice',
                        'title' => 'Total Price',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => true,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'numeric',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'width' => '',
                        'defaultValue' => null,
                        'integer' => false,
                        'unsigned' => true,
                        'minValue' => 0,
                        'maxValue' => null,
                        'unique' => false,
                        'decimalSize' => 10,
                        'decimalPrecision' => 2,
                    ]),
                ],
                'locked' => false,
                'fieldtype' => 'panel',
                'layout' => null,
                'border' => false,
            ]),
        ],
        'locked' => false,
        'fieldtype' => 'panel',
        'layout' => null,
        'border' => false,
    ]),
    'icon' => null,
    'group' => null,
    'showAppLoggerTab' => false,
    'linkGeneratorReference' => null,
    'previewGeneratorReference' => null,
    'compositeIndices' => [],
    'showFieldLookup' => false,
    'propertyVisibility' => [
        'grid' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
        'search' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
    ],
    'enableGridLocking' => false,
]);
