<?php

/**
 * Inheritance: no
 * Variants: no
 *
 * Fields Summary:
 * - name [input]
 * - address [textarea]
 * - capacity [numeric]
 * - photos [imageGallery]
 */

return \Pimcore\Model\DataObject\ClassDefinition::__set_state([
    'id' => 'venue',
    'name' => 'Venue',
    'title' => '',
    'description' => '',
    'creationDate' => null,
    'modificationDate' => null,
    'userOwner' => null,
    'userModification' => null,
    'parentClass' => '',
    'implementsInterfaces' => null,
    'listingParentClass' => '',
    'useTraits' => '',
    'listingUseTraits' => '',
    'allowInherit' => false,
    'allowVariants' => false,
    'showVariants' => false,
    'layoutDefinitions' =>
    \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
        'name' => 'pimcore_root',
        'type' => null,
        'region' => null,
        'title' => null,
        'width' => 0,
        'height' => 0,
        'collapsible' => false,
        'collapsed' => false,
        'bodyStyle' => null,
        'datatype' => 'layout',
        'permissions' => null,
        'children' => [
            \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
                'name' => 'Layout',
                'type' => null,
                'region' => null,
                'title' => '',
                'width' => 0,
                'height' => 0,
                'collapsible' => false,
                'collapsed' => false,
                'bodyStyle' => null,
                'datatype' => 'layout',
                'permissions' => null,
                'children' => [
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state([
                        'name' => 'name',
                        'title' => 'Name',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'input',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => true,
                        'maxLength' => 255,
                        'showCharCount' => false,
                        'columnLength' => 190,
                        'defaultValue' => '',
                        'enforceUniqueValues' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Textarea::__set_state([
                        'name' => 'address',
                        'title' => 'Address',
                        'tooltip' => '',
                        'mandatory' => false,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'textarea',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => false,
                        'visibleSearch' => false,
                        'maxLength' => null,
                        'showCharCount' => false,
                        'height' => 100,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state([
                        'name' => 'capacity',
                        'title' => 'Capacity',
                        'tooltip' => '',
                        'mandatory' => false,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'numeric',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'width' => '',
                        'defaultValue' => null,
                        'integer' => true,
                        'unsigned' => true,
                        'minValue' => null,
                        'maxValue' => null,
                        'unique' => false,
                        'decimalSize' => null,
                        'decimalPrecision' => null,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\ImageGallery::__set_state([
                        'name' => 'photos',
                        'title' => 'Photos',
                        'tooltip' => '',
                        'mandatory' => false,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'imageGallery',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => false,
                        'visibleSearch' => false,
                        'uploadPath' => '',
                        'ratioX' => null,
                        'ratioY' => null,
                        'predefinedDataTemplates' => '',
                    ]),
                ],
                'locked' => false,
                'fieldtype' => 'panel',
                'layout' => null,
                'border' => false,
            ]),
        ],
        'locked' => false,
        'fieldtype' => 'panel',
        'layout' => null,
        'border' => false,
    ]),
    'icon' => null,
    'group' => null,
    'showAppLoggerTab' => false,
    'linkGeneratorReference' => null,
    'previewGeneratorReference' => null,
    'compositeIndices' => [],
    'showFieldLookup' => false,
    'propertyVisibility' => [
        'grid' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
        'search' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
    ],
    'enableGridLocking' => false,
]);
