<?php

/**
 * Inheritance: no
 * Variants: no
 *
 * Fields Summary:
 * - name [input]
 * - slug [input]
 * - description [textarea]
 * - startDate [date]
 * - endDate [date]
 * - venue [manyToOneRelation]
 * - heroImage [image]
 * - status [select]
 */

return \Pimcore\Model\DataObject\ClassDefinition::__set_state([
    'id' => 'event',
    'name' => 'Event',
    'title' => '',
    'description' => '',
    'creationDate' => null,
    'modificationDate' => null,
    'userOwner' => null,
    'userModification' => null,
    'parentClass' => '',
    'implementsInterfaces' => null,
    'listingParentClass' => '',
    'useTraits' => '',
    'listingUseTraits' => '',
    'allowInherit' => false,
    'allowVariants' => false,
    'showVariants' => false,
    'layoutDefinitions' =>
    \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
        'name' => 'pimcore_root',
        'type' => null,
        'region' => null,
        'title' => null,
        'width' => 0,
        'height' => 0,
        'collapsible' => false,
        'collapsed' => false,
        'bodyStyle' => null,
        'datatype' => 'layout',
        'permissions' => null,
        'children' => [
            \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
                'name' => 'Layout',
                'type' => null,
                'region' => null,
                'title' => '',
                'width' => 0,
                'height' => 0,
                'collapsible' => false,
                'collapsed' => false,
                'bodyStyle' => null,
                'datatype' => 'layout',
                'permissions' => null,
                'children' => [
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state([
                        'name' => 'name',
                        'title' => 'Name',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'input',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => true,
                        'maxLength' => 255,
                        'showCharCount' => false,
                        'columnLength' => 190,
                        'defaultValue' => '',
                        'enforceUniqueValues' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state([
                        'name' => 'slug',
                        'title' => 'Slug',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'input',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'maxLength' => 255,
                        'showCharCount' => false,
                        'columnLength' => 190,
                        'defaultValue' => '',
                        'enforceUniqueValues' => true,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Textarea::__set_state([
                        'name' => 'description',
                        'title' => 'Description',
                        'tooltip' => '',
                        'mandatory' => false,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'textarea',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => false,
                        'visibleSearch' => false,
                        'maxLength' => null,
                        'showCharCount' => false,
                        'height' => 150,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Date::__set_state([
                        'name' => 'startDate',
                        'title' => 'Start Date',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'date',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'defaultValue' => null,
                        'useCurrentDate' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Date::__set_state([
                        'name' => 'endDate',
                        'title' => 'End Date',
                        'tooltip' => '',
                        'mandatory' => false,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'date',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'defaultValue' => null,
                        'useCurrentDate' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\ManyToOneRelation::__set_state([
                        'name' => 'venue',
                        'title' => 'Venue',
                        'tooltip' => '',
                        'mandatory' => false,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'manyToOneRelation',
                        'relationType' => true,
                        'invisible' => false,
                        'visibleGridView' => false,
                        'visibleSearch' => false,
                        'classes' => [
                            ['classes' => 'Venue'],
                        ],
                        'assetTypes' => [],
                        'documentTypes' => [],
                        'objectsAllowed' => true,
                        'assetsAllowed' => false,
                        'documentsAllowed' => false,
                        'assetInlineDownloadAllowed' => false,
                        'allowToClearRelation' => true,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Image::__set_state([
                        'name' => 'heroImage',
                        'title' => 'Hero Image',
                        'tooltip' => '',
                        'mandatory' => false,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'image',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => false,
                        'visibleSearch' => false,
                        'uploadPath' => '',
                        'thumbnail' => '',
                        'minWidth' => null,
                        'minHeight' => null,
                        'maxWidth' => null,
                        'maxHeight' => null,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state([
                        'name' => 'status',
                        'title' => 'Status',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'select',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => true,
                        'options' => [
                            ['key' => 'Draft',     'value' => 'draft'],
                            ['key' => 'Published', 'value' => 'published'],
                            ['key' => 'Sold Out',  'value' => 'soldout'],
                            ['key' => 'Cancelled', 'value' => 'cancelled'],
                        ],
                        'defaultValue' => 'draft',
                        'columnLength' => 190,
                        'dynamicOptions' => false,
                        'enforceValidation' => true,
                    ]),
                ],
                'locked' => false,
                'fieldtype' => 'panel',
                'layout' => null,
                'border' => false,
            ]),
        ],
        'locked' => false,
        'fieldtype' => 'panel',
        'layout' => null,
        'border' => false,
    ]),
    'icon' => null,
    'group' => null,
    'showAppLoggerTab' => false,
    'linkGeneratorReference' => null,
    'previewGeneratorReference' => null,
    'compositeIndices' => [],
    'showFieldLookup' => false,
    'propertyVisibility' => [
        'grid' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
        'search' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
    ],
    'enableGridLocking' => false,
]);
