<?php

/**
 * Inheritance: no
 * Variants: no
 *
 * Fields Summary:
 * - name [input]
 * - price [numeric]
 * - currency [select]
 * - quota [numeric]
 * - salesStart [datetime]
 * - salesEnd [datetime]
 * - event [manyToOneRelation]
 */

return \Pimcore\Model\DataObject\ClassDefinition::__set_state([
    'id' => 'tickettier',
    'name' => 'TicketTier',
    'title' => '',
    'description' => '',
    'creationDate' => null,
    'modificationDate' => null,
    'userOwner' => null,
    'userModification' => null,
    'parentClass' => '',
    'implementsInterfaces' => null,
    'listingParentClass' => '',
    'useTraits' => '',
    'listingUseTraits' => '',
    'allowInherit' => false,
    'allowVariants' => false,
    'showVariants' => false,
    'layoutDefinitions' =>
    \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
        'name' => 'pimcore_root',
        'type' => null,
        'region' => null,
        'title' => null,
        'width' => 0,
        'height' => 0,
        'collapsible' => false,
        'collapsed' => false,
        'bodyStyle' => null,
        'datatype' => 'layout',
        'permissions' => null,
        'children' => [
            \Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state([
                'name' => 'Layout',
                'type' => null,
                'region' => null,
                'title' => '',
                'width' => 0,
                'height' => 0,
                'collapsible' => false,
                'collapsed' => false,
                'bodyStyle' => null,
                'datatype' => 'layout',
                'permissions' => null,
                'children' => [
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state([
                        'name' => 'name',
                        'title' => 'Name',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'input',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => true,
                        'maxLength' => 255,
                        'showCharCount' => false,
                        'columnLength' => 190,
                        'defaultValue' => '',
                        'enforceUniqueValues' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state([
                        'name' => 'price',
                        'title' => 'Price',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'numeric',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'width' => '',
                        'defaultValue' => null,
                        'integer' => false,
                        'unsigned' => true,
                        'minValue' => 0,
                        'maxValue' => null,
                        'unique' => false,
                        'decimalSize' => 10,
                        'decimalPrecision' => 2,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state([
                        'name' => 'currency',
                        'title' => 'Currency',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'select',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'options' => [
                            ['key' => 'EUR', 'value' => 'EUR'],
                            ['key' => 'USD', 'value' => 'USD'],
                            ['key' => 'GBP', 'value' => 'GBP'],
                        ],
                        'defaultValue' => 'EUR',
                        'columnLength' => 190,
                        'dynamicOptions' => false,
                        'enforceValidation' => true,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state([
                        'name' => 'quota',
                        'title' => 'Quota',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => false,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'numeric',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'width' => '',
                        'defaultValue' => null,
                        'integer' => true,
                        'unsigned' => true,
                        'minValue' => 1,
                        'maxValue' => null,
                        'unique' => false,
                        'decimalSize' => null,
                        'decimalPrecision' => null,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Datetime::__set_state([
                        'name' => 'salesStart',
                        'title' => 'Sales Start',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'datetime',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'defaultValue' => null,
                        'useCurrentDate' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\Datetime::__set_state([
                        'name' => 'salesEnd',
                        'title' => 'Sales End',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'datetime',
                        'relationType' => false,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'defaultValue' => null,
                        'useCurrentDate' => false,
                    ]),
                    \Pimcore\Model\DataObject\ClassDefinition\Data\ManyToOneRelation::__set_state([
                        'name' => 'event',
                        'title' => 'Event',
                        'tooltip' => '',
                        'mandatory' => true,
                        'noteditable' => false,
                        'index' => true,
                        'locked' => false,
                        'style' => '',
                        'permissions' => null,
                        'fieldtype' => 'manyToOneRelation',
                        'relationType' => true,
                        'invisible' => false,
                        'visibleGridView' => true,
                        'visibleSearch' => false,
                        'classes' => [
                            ['classes' => 'Event'],
                        ],
                        'assetTypes' => [],
                        'documentTypes' => [],
                        'objectsAllowed' => true,
                        'assetsAllowed' => false,
                        'documentsAllowed' => false,
                        'assetInlineDownloadAllowed' => false,
                        'allowToClearRelation' => false,
                    ]),
                ],
                'locked' => false,
                'fieldtype' => 'panel',
                'layout' => null,
                'border' => false,
            ]),
        ],
        'locked' => false,
        'fieldtype' => 'panel',
        'layout' => null,
        'border' => false,
    ]),
    'icon' => null,
    'group' => null,
    'showAppLoggerTab' => false,
    'linkGeneratorReference' => null,
    'previewGeneratorReference' => null,
    'compositeIndices' => [],
    'showFieldLookup' => false,
    'propertyVisibility' => [
        'grid' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
        'search' => [
            'id' => true,
            'path' => true,
            'published' => true,
            'modificationDate' => true,
            'creationDate' => true,
        ],
    ],
    'enableGridLocking' => false,
]);
